
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = RESTAURANTE;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE detalle_factura CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE factura CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE mesa CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE supervisor CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE mesero CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE cliente CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE cliente (
  id_cliente NUMBER(10,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identificacion VARCHAR2(15) NOT NULL UNIQUE,
  nombres VARCHAR2(100) NOT NULL,
  apellidos VARCHAR2(100) NOT NULL,
  direccion VARCHAR2(200),
  telefono VARCHAR2(30),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP
);

CREATE TABLE mesero (
  id_mesero NUMBER(10,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombres VARCHAR2(100) NOT NULL,
  apellidos VARCHAR2(100) NOT NULL,
  edad NUMBER(10,0),
  antiguedad NUMBER(10,0),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP
);

CREATE TABLE supervisor (
  id_supervisor NUMBER(10,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombres VARCHAR2(100) NOT NULL,
  apellidos VARCHAR2(100) NOT NULL,
  edad NUMBER(10,0),
  antiguedad NUMBER(10,0),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP
);

CREATE TABLE mesa (
  id_mesa NUMBER(10,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nro_mesa NUMBER(10,0) NOT NULL UNIQUE,
  nombre VARCHAR2(100),
  reservada NUMBER(1) NOT NULL,
  puestos NUMBER(10,0) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP
);

CREATE TABLE factura (
  id_factura NUMBER(10,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nro_factura NUMBER(10,0) NOT NULL UNIQUE,
  id_cliente NUMBER(10,0) NOT NULL,
  id_mesa NUMBER(10,0) NOT NULL,
  id_mesero NUMBER(10,0) NOT NULL,
  fecha DATE NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  CONSTRAINT fk_factura_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
  CONSTRAINT fk_factura_mesa FOREIGN KEY (id_mesa) REFERENCES mesa(id_mesa),
  CONSTRAINT fk_factura_mesero FOREIGN KEY (id_mesero) REFERENCES mesero(id_mesero)
);

CREATE TABLE detalle_factura (
  id_detalle_factura NUMBER(10,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_factura NUMBER(10,0) NOT NULL,
  id_supervisor NUMBER(10,0) NOT NULL,
  plato VARCHAR2(150) NOT NULL,
  valor NUMBER(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  CONSTRAINT fk_detalle_factura FOREIGN KEY (id_factura) REFERENCES factura(id_factura),
  CONSTRAINT fk_detalle_supervisor FOREIGN KEY (id_supervisor) REFERENCES supervisor(id_supervisor)
);

CREATE INDEX idx_factura_cliente ON factura(id_cliente);
CREATE INDEX idx_factura_mesero ON factura(id_mesero);
CREATE INDEX idx_factura_fecha ON factura(fecha);
CREATE INDEX idx_detalle_factura ON detalle_factura(id_factura);
CREATE INDEX idx_detalle_supervisor ON detalle_factura(id_supervisor);